# Generated by Django 4.2.16 on 2026-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_add_in_progress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='processing_stage',
            field=models.CharField(default='queued', max_length=20),
        ),
    ]
